In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score
from sklearn.linear_model import Ridge

In [2]:
df = pd.read_csv('2021_2022_NHL_SCHEDULE.csv', skiprows = 0,)
df

,Date,Visitor,visitor_goals,Home,home_goals,goals_difference
0,10/12/2021,Pittsburgh Penguins,6,Tampa Bay Lightning,2,NaN
1,10/12/2021,Seattle Kraken,3,Vegas Golden Knights,4,NaN
2,10/13/2021,Winnipeg Jets,1,Anaheim Ducks,4,NaN
3,10/13/2021,Chicago Blackhawks,2,Colorado Avalanche,4,NaN
4,10/13/2021,Vancouver Canucks,2,Edmonton Oilers,3,NaN
...,...,...,...,...,...,...
1307,4/29/2022,San Jose Sharks,0,Seattle Kraken,3,NaN
1308,4/29/2022,Vegas Golden Knights,7,St. Louis Blues,4,NaN
1309,4/29/2022,Boston Bruins,2,Toronto Maple Leafs,5,NaN
1310,4/29/2022,Calgary Flames,1,Winnipeg Jets,3,NaN
1311,5/1/2022,Seattle Kraken,3,Winnipeg Jets,4,NaN

In [3]:
df['goal_difference'] = df['home_goals'] - df['visitor_goals']

In [4]:
df['home_win'] = np.where(df['goal_difference'] > 0, 1, 0)
df['home_loss'] = np.where(df['goal_difference'] < 0, 1, 0)

In [5]:
df

,Date,Visitor,visitor_goals,Home,home_goals,goals_difference,goal_difference,home_win,home_loss
0,10/12/2021,Pittsburgh Penguins,6,Tampa Bay Lightning,2,NaN,-4,0,1
1,10/12/2021,Seattle Kraken,3,Vegas Golden Knights,4,NaN,1,1,0
2,10/13/2021,Winnipeg Jets,1,Anaheim Ducks,4,NaN,3,1,0
3,10/13/2021,Chicago Blackhawks,2,Colorado Avalanche,4,NaN,2,1,0
4,10/13/2021,Vancouver Canucks,2,Edmonton Oilers,3,NaN,1,1,0
...,...,...,...,...,...,...,...,...,...
1307,4/29/2022,San Jose Sharks,0,Seattle Kraken,3,NaN,3,1,0
1308,4/29/2022,Vegas Golden Knights,7,St. Louis Blues,4,NaN,-3,0,1
1309,4/29/2022,Boston Bruins,2,Toronto Maple Leafs,5,NaN,3,1,0
1310,4/29/2022,Calgary Flames,1,Winnipeg Jets,3,NaN,2,1,0
1311,5/1/2022,Seattle Kraken,3,Winnipeg Jets,4,NaN,1,1,0

In [7]:
df_visitor = pd.get_dummies(df['Visitor'], dtype=np.int64)
df_home = pd.get_dummies(df['Home'], dtype=np.int64)

In [9]:
df_model = df_home.sub(df_visitor) 
df_model['goal_difference'] = df['goal_difference']

In [11]:
df_train = df_model

lr = Ridge(alpha=0.001) 
X = df_train.drop(['goal_difference'], axis=1)
y = df_train['goal_difference']

lr.fit(X, y)

Ridge(alpha=0.001)

In [12]:
df_ratings = pd.DataFrame(data={'team': X.columns, 'rating': lr.coef_})
df_ratings

                     team    rating
0           Anaheim Ducks -0.444524
1         Arizona Coyotes -1.233467
2           Boston Bruins  0.376602
3          Buffalo Sabres -0.686525
4          Calgary Flames  0.990666
5     Carolina Hurricanes  0.874775
6      Chicago Blackhawks -0.826609
7      Colorado Avalanche  0.907852
8   Columbus Blue Jackets -0.440835
9            Dallas Stars -0.084846
10      Detroit Red Wings -0.944834
11        Edmonton Oilers  0.461348
12       Florida Panthers  1.070712
13      Los Angeles Kings  0.026523
14         Minnesota Wild  0.677025
15     Montreal Canadiens -1.145817
16    Nashville Predators  0.186735
17      New Jersey Devils -0.682726
18     New York Islanders -0.089920
19       New York Rangers  0.543282
20        Ottawa Senators -0.444361
21    Philadelphia Flyers -1.002876
22    Pittsburgh Penguins  0.486544
23        San Jose Sharks -0.580666
24         Seattle Kraken -0.797461
25        St. Louis Blues  0.793008
26    Tampa Bay Lightning  0.639359
27    Toronto Maple Leafs  0.694246
28      Vancouver Canucks  0.162655
29   Vegas Golden Knights  0.209583
30    Washington Capitals  0.346131
31          Winnipeg Jets -0.041578